### ISSUE TITLE
Unable to Load Model

### ISSUE THREAD

**Issue by mmcdermott1** [RF5/simple-speaker-embedding#2]
I am unable to load the model.
Has it been removed?

<img width="777" alt="Screen Shot 2022-05-28 at 8 22 24 PM" src="https://user-images.githubusercontent.com/35214918/170846886-ef9608bf-b038-4aa1-b4e0-d951934da51d.png">

**Comment by RF5** [comment]
Hi, I am having trouble replicating your error. When I try the same code in colab it appears to work fine? (see image)
![image](https://user-images.githubusercontent.com/23717819/170857315-dbc22878-d813-4d1c-9056-129ae993bf43.png)
Can you give me more information about the environment you are using (python, torch. cuda version?). Does it work if you try load it to cpu with the `device="cpu"` argument?

**Comment by RF5** [comment]
Closing since this issue seems dead, feel free to open if you still have the issue.
