### ISSUE TITLE
Question: How can I generate the embedding projection graph

### ISSUE THREAD

**Issue by wovalle** [RF5/simple-speaker-embedding#6]
Note: this is not an issue, but is the only places that I can ask a question given than Github Discussions are disabled for this repo. I'm new with ML Models (and data science in general) and my language might not be correct, apologize for that.

First of all great project!

I'm running the example code with some wav files and it "seems" to be working but I want to see how "similar" certain voices are to each other. I understand I need to take both tensors and get the cosine similarity but I'm not getting the info I need 😅 How can I generate the following graph?

![IMG_1146](https://raw.githubusercontent.com/RF5/simple-speaker-embedding/master/imgs/tsne-embedding.svg)

Thanks!

**Comment by RF5** [comment]
Hi @wovalle , sure thing. That plot is generating using T-SNE, a visualization techinque for high-dimensional data. There are many good libraries to compute it, such as [sklearn here](https://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html). 

So, simply compute the embeddings for all the utterances you'd like, stack them into a matrix, and then call the function above to yield the 2D points output, which you can then plot with matplotlib.

Hope that helps!
